export const DEFAULT_LOCATION = "Canada";
export const datePostedOptions = ["all", "today", "3days", "week", "month"];
export const DEFAULT_TYPE = "L2J1c2luZXNzL25haWNzMjAwNy81MTpJbmZvcm1hdGlvbg==";
export const filters = {
  data: {
    employment_types: [
      {
        name: "Full-time",
        value: "FULLTIME",
      },
      {
        name: "Part-time",
        value: "PARTTIME",
      },
      {
        name: "Contract",
        value: "CONTRACTOR",
      },
      {
        name: "Internship",
        value: "INTERN",
      },
    ],
    date_posted: [
      {
        name: "Past day",
        value: "today",
      },
      {
        name: "Past 3 days",
        value: "3days",
      },
      {
        name: "Past week",
        value: "week",
      },
      {
        name: "Past month",
        value: "month",
      },
    ],
    job_requirements: [
      {
        name: "No degree",
        value: "no_degree",
      },
      {
        name: "No experience",
        value: "no_experience",
      },
      {
        name: "Under 3 years of experience",
        value: "under_3_years_experience",
      },
      {
        name: "3+ years of experience",
        value: "more_than_3_years_experience",
      },
    ],
    remote: [
      {
        name: "Remote Jobs Only",
        value: "true",
      },
    ],
  },
};
export const programmingLanguages: string[] = [
  "ABAP",
  "ASP.NET Core",
  "ActionScript",
  "Ada",
  "Adobe XD",
  "Angular",
  "Ant",
  "Apache Cordova",
  "Apache Spark",
  "Apex",
  "Assembly",
  "Axure",
  "Babel",
  "Backbone.js",
  "Ballerina",
  "Bash",
  "Blazor",
  "Bootstrap",
  "Bulma",
  "C#",
  "C++",
  "COBOL",
  "Chai",
  "Clojure",
  "Cobol",
  "CoffeeScript",
  "Common Lisp",
  "Cordova",
  "CryEngine",
  "Crystal",
  "Cucumber",
  "D3.js",
  "Dart",
  "Delphi",
  "Django",
  "Electron",
  "Elixir",
  "Elm",
  "Ember.js",
  "Entity Framework",
  "Enzyme",
  "Erlang",
  "Express",
  "F#",
  "F*",
  "FastAPI",
  "Figma",
  "Flask",
  "Flutter",
  "Fortran",
  "Foundation",
  "GTK",
  "Gatsby",
  "Go",
  "Godot",
  "Gradle",
  "Groovy",
  "Grunt",
  "Gulp",
  "Hack",
  "Hadoop",
  "Haskell",
  "Hibernate",
  "InVision",
  "Ionic",
  "JQuery",
  "JUnit",
  "Java",
  "JavaScript",
  "Jekyll",
  "Jest",
  "Julia",
  "Keras",
  "Kotlin",
  "Laravel",
  "Lua",
  "MATLAB",
  "Materialize",
  "Matplotlib",
  "Maven",
  "Meteor",
  "Mocha",
  "Next.js",
  "NumPy",
  "Nuxt.js",
  "OCaml",
  "Objective-C",
  "OpenGL",
  "PHP",
  "PL/SQL",
  "PL/pgSQL",
  "Pandas",
  "Pascal",
  "Perl",
  "PhoneGap",
  "PowerShell",
  "Prolog",
  "Proto.io",
  "PyTorch",
  "Python",
  "Qt",
  "R",
  "RPG",
  "RSpec",
  "Racket",
  "React",
  "React Native",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "SAS",
  "SQL",
  "Scala",
  "Scheme",
  "SciPy",
  "Scikit-learn",
  "Selenium",
  "Shell",
  "Sketch",
  "Solidity",
  "Spring",
  "Struts",
  "Svelte",
  "Swift",
  "SwiftUI",
  "Symfony",
  "T-SQL",
  "Tailwind CSS",
  "TensorFlow",
  "Three.js",
  "Thymeleaf",
  "TypeScript",
  "Unity",
  "Unreal Engine",
  "VB.NET",
  "VBA",
  "Vue.js",
  "WPF",
  "Webpack",
  "Xamarin",
];
